/**
 * @module useArticleGeneration
 * @description Custom hook for managing AI-powered article generation and data processing
 *
 * This hook orchestrates the article generation workflow:
 * 1. **Modal Management**: Controls the article generator modal state
 * 2. **Data Processing**: Processes AI-generated article data
 * 3. **Slug Generation**: Auto-generates SEO-friendly slugs
 * 4. **FAQ Processing**: Ensures all FAQ items have unique IDs
 * 5. **Form Update**: Updates form with all generated content
 *
 * **Integration Points:**
 * - Works with ArticleGeneratorModal component for user input
 * - Processes output from AI article generation API
 * - Updates parent form via updateFormData callback
 *
 * **Data Transformations:**
 * - Generates slug from title + category using SEO-friendly algorithm
 * - Adds unique IDs to FAQ items for React key management
 * - Preserves existing image if no new imagePrompt provided
 *
 * @see {@link /app/admin/blog/_components/BlogPostForm.tsx} - Main consumer
 * @see {@link /app/admin/blog/_components/ArticleGeneratorModal.tsx} - Modal UI
 * @see {@link /app/admin/blog/_utils/generateSlug.ts} - Slug generation utility
 *
 * @example
 * ```tsx
 * const {
 *   isGeneratorModalOpen,
 *   setIsGeneratorModalOpen,
 *   handleGenerateArticleData,
 * } = useArticleGeneration(updateFormData, currentImage);
 *
 * // Open modal
 * <button onClick={() => setIsGeneratorModalOpen(true)}>
 *   Generate Article
 * </button>
 *
 * // Process generated data
 * <ArticleGeneratorModal
 *   isOpen={isGeneratorModalOpen}
 *   onClose={() => setIsGeneratorModalOpen(false)}
 *   onGenerateData={handleGenerateArticleData}
 * />
 * ```
 */

import { useCallback, useState } from "react";
import { useToast } from "@/lib/toast-context";
import { generateSlugFromTitleAndCategory } from "../_utils/generateSlug";
import type { FAQItem } from "@/lib/blog";

/**
 * Generated article data structure returned by AI
 *
 * This type represents the complete article data generated by the AI,
 * including all metadata, content, and optional fields for SEO and image generation.
 *
 * @property {string} title - Generated article title
 * @property {string} description - Generated meta description
 * @property {string} category - Article category
 * @property {string} content - Main article content in Markdown
 * @property {string[]} tags - Array of relevant tags
 * @property {FAQItem[]} faq - Frequently asked questions
 * @property {string} [imagePrompt] - Optional AI image generation prompt
 * @property {string} [seoIntent] - Optional SEO search intent
 * @property {string} [persona] - Optional target audience persona
 * @property {string[]} [tones] - Optional writing tones used
 */
export type GeneratedArticleData = {
  title: string;
  description: string;
  category: string;
  content: string;
  tags: string[];
  faq: FAQItem[];
  imagePrompt?: string;
  seoIntent?: string;
  persona?: string;
  tones?: string[];
};

/**
 * Form data structure for image generation
 */
interface ImageGenerationFormData {
  title: string;
  content: string;
  slug?: string;
  category: string;
  tags: string[];
  seoIntent?: string;
  persona?: string;
  tones?: string[];
  imagePrompt?: string;
  image?: string;
}

/**
 * Custom hook for managing AI article generation workflow
 *
 * Handles the article generator modal state and processes generated article data.
 * Automatically generates SEO-friendly slugs and ensures FAQ items have proper IDs.
 *
 * **Processing Pipeline:**
 * 1. Receives generated article data from modal
 * 2. Generates SEO-friendly slug from title + category
 * 3. Checks if slug already exists and generates unique one if needed
 * 4. Ensures all FAQ items have unique IDs
 * 5. Sets image path if imagePrompt exists
 * 6. Updates form with all processed data
 * 7. Closes generator modal
 * 8. Shows success notification
 * 9. Automatically triggers image generation if no image exists
 *
 * **Slug Generation:**
 * Uses generateSlugFromTitleAndCategory utility which:
 * - Combines category prefix with title keywords
 * - Removes stop words and special characters
 * - Creates URL-friendly format (lowercase, hyphens)
 * - Verifies uniqueness via API and adds suffix if needed
 *
 * **FAQ ID Management:**
 * Ensures each FAQ has a unique ID for React rendering:
 * - Preserves existing IDs if present
 * - Generates new IDs using timestamp + index
 * - Format: "faq-{timestamp}-{index}"
 *
 * **Auto Image Generation:**
 * After article generation, if imagePrompt exists and no image is set,
 * automatically triggers image generation via the provided callback.
 *
 * @param {Function} updateFormData - Callback to partially update form data
 * @param {string} [currentImage] - Current image value to preserve if no imagePrompt
 * @param {Function} [onAutoGenerateImage] - Optional callback to trigger automatic image generation
 * @returns {Object} Article generation interface
 * @returns {boolean} isGeneratorModalOpen - Modal visibility state
 * @returns {Function} setIsGeneratorModalOpen - Control modal visibility
 * @returns {Function} handleGenerateArticleData - Process and apply generated data
 *
 * @example
 * ```tsx
 * const {
 *   isGeneratorModalOpen,
 *   setIsGeneratorModalOpen,
 *   handleGenerateArticleData,
 * } = useArticleGeneration(updateFormData, currentImage, generateImageFromArticleData);
 *
 * // Open modal
 * <button onClick={() => setIsGeneratorModalOpen(true)}>
 *   Generate Article
 * </button>
 *
 * // Handle generated data
 * <ArticleGeneratorModal
 *   isOpen={isGeneratorModalOpen}
 *   onClose={() => setIsGeneratorModalOpen(false)}
 *   onGenerateData={handleGenerateArticleData}
 * />
 * ```
 */
export function useArticleGeneration(
  updateFormData: (update: any) => void,
  currentImage?: string,
  onAutoGenerateImage?: (articleData: ImageGenerationFormData) => Promise<void>
) {
  const { addToast } = useToast();

  // State for article generator modal visibility
  const [isGeneratorModalOpen, setIsGeneratorModalOpen] = useState(false);

  /**
   * Handle generated article data from AI
   *
   * Processes the generated article by:
   * 1. Generating a SEO-friendly slug from title and category
   * 2. Checking if slug exists and getting unique one if needed
   * 3. Ensuring all FAQ items have unique IDs
   * 4. Setting the image path based on imagePrompt
   * 5. Updating the form with all generated data
   * 6. Closing the generator modal
   * 7. Showing success notification
   *
   * **Slug Generation Logic:**
   * The slug is generated using a combination of category and title:
   * - Extracts important keywords from title
   * - Removes French stop words (le, la, les, etc.)
   * - Prepends category for better SEO and organization
   * - Example: "Comprendre" + "L'anxiété et ses causes" → "comprendre-anxiete-causes"
   * - If slug already exists, adds numeric suffix (e.g., "-2", "-3")
   *
   * **FAQ ID Generation:**
   * Each FAQ needs a unique ID for React's key prop:
   * - If FAQ already has ID (from API), preserve it
   * - Otherwise, generate new ID: faq-{timestamp}-{index}
   * - Timestamp ensures uniqueness across generations
   *
   * **Image Path Logic:**
   * - If imagePrompt exists: Set image path to /images/blog/{slug}.webp
   *   (This path will be used after user generates and selects image)
   * - If no imagePrompt: Preserve currentImage value
   *   (Maintains existing image when regenerating article content)
   *
   * @param {GeneratedArticleData} article - The generated article data from AI
   */
  const handleGenerateArticleData = useCallback(async (article: GeneratedArticleData) => {
    // Step 1: Generate a SEO-friendly slug combining category and key terms from title
    // This creates URLs like: /blog/comprendre-anxiete-causes
    const baseSlug = generateSlugFromTitleAndCategory(article.title, article.category);

    // Step 2: Check if slug already exists and get a unique one if needed
    let finalSlug = baseSlug;
    try {
      const checkResponse = await fetch(
        `/api/blog/posts/check-slug?slug=${encodeURIComponent(baseSlug)}`
      );
      if (checkResponse.ok) {
        const { exists, suggestedSlug } = await checkResponse.json();
        if (exists) {
          finalSlug = suggestedSlug;
          addToast({
            title: "Slug modifié",
            description: `Un article avec le slug "${baseSlug}" existe déjà. Nouveau slug : "${finalSlug}"`,
            variant: "info",
          });
        }
      }
    } catch (slugCheckError) {
      console.warn("Erreur vérification slug, utilisation du slug généré:", slugCheckError);
    }

    // Step 3: Ensure each FAQ has a unique ID for React rendering
    // This prevents React key warnings and enables proper list management
    const faqWithIds = article.faq.map((item, index) => ({
      ...item,
      // Keep existing ID if present, otherwise generate new one
      id: item.id || `faq-${Date.now()}-${index}`,
    }));

    // Step 4: Check if article has no image - we'll auto-generate one
    const shouldAutoGenerateImage = !currentImage && article.imagePrompt;

    // Step 5: Update form data with all generated content
    // Don't set image path yet if we'll auto-generate (keep it empty until image is selected)
    updateFormData({
      title: article.title,
      slug: finalSlug,
      description: article.description,
      category: article.category,
      content: article.content,
      tags: article.tags,
      faq: faqWithIds,
      // Keep current image if exists, otherwise leave empty for auto-generation
      image: currentImage || "",
      imagePrompt: article.imagePrompt || "",
      seoIntent: article.seoIntent || "",
      persona: article.persona || "",
      tones: article.tones || [],
    });

    // Step 6: Close the generator modal
    setIsGeneratorModalOpen(false);

    // Step 7: Show success notification to user
    addToast({
      title: "Article généré avec succès",
      variant: "success",
    });

    // Step 8: Auto-generate image if no image exists and imagePrompt is available
    if (shouldAutoGenerateImage && onAutoGenerateImage) {
      // Prepare article data for image generation
      const imageGenerationData: ImageGenerationFormData = {
        title: article.title,
        content: article.content,
        slug: finalSlug,
        category: article.category,
        tags: article.tags,
        seoIntent: article.seoIntent,
        persona: article.persona,
        tones: article.tones,
        imagePrompt: article.imagePrompt,
      };

      // Trigger automatic image generation
      // Using setTimeout to ensure form state is updated before starting image generation
      setTimeout(() => {
        addToast({
          title: "Génération automatique de l'image...",
          description: "L'article n'a pas d'image, génération en cours",
          variant: "info",
        });
        onAutoGenerateImage(imageGenerationData);
      }, 100);
    }
  }, [updateFormData, currentImage, addToast, onAutoGenerateImage]);

  return {
    isGeneratorModalOpen,
    setIsGeneratorModalOpen,
    handleGenerateArticleData,
  };
}
