/**
 * @module useImageGeneration
 * @description Custom hook for managing AI-powered image generation and selection workflow
 *
 * This hook orchestrates a complete image generation pipeline:
 * 1. **Prompt Generation**: AI analyzes article content to create image prompts
 * 2. **Image Generation**: DALL-E creates 3 image proposals based on prompt
 * 3. **Selection Modal**: User previews and selects preferred image
 * 4. **Confirmation**: Selected image is moved from temp to final location
 * 5. **Regeneration**: User can regenerate if not satisfied with proposals
 *
 * **State Management:**
 * - Tracks multiple async operations independently
 * - Manages modal visibility for image selection
 * - Stores temporary image proposals until confirmation
 *
 * **API Endpoints:**
 * - POST /api/blog/generate-prompt - Generate image prompt from article
 * - POST /api/blog/generate-image - Generate 3 DALL-E images
 * - POST /api/blog/confirm-image-selection - Move selected image to final location
 *
 * @see {@link /app/admin/blog/_components/BlogPostForm.tsx} - Main consumer
 * @see {@link /app/admin/blog/_components/ImageSelectionModal.tsx} - Selection UI
 * @see {@link /app/api/blog/generate-prompt/route.ts} - Prompt generation API
 * @see {@link /app/api/blog/generate-image/route.ts} - Image generation API
 * @see {@link /app/api/blog/confirm-image-selection/route.ts} - Confirmation API
 *
 * @example
 * ```tsx
 * const {
 *   isGeneratingPrompt,
 *   isGeneratingImages,
 *   imageProposals,
 *   isImageSelectionOpen,
 *   generateImagePrompt,
 *   generateImages,
 *   confirmImageSelection,
 *   regenerateImages,
 * } = useImageGeneration(formData, updateFormData);
 *
 * // Generate prompt from article content
 * await generateImagePrompt();
 *
 * // Generate images (requires prompt and slug)
 * await generateImages();
 *
 * // Show selection modal
 * {isImageSelectionOpen && <ImageSelectionModal proposals={imageProposals} />}
 *
 * // Confirm selection
 * await confirmImageSelection(selectedProposal);
 * ```
 */

import { useState, useCallback } from "react";
import { useToast } from "@/lib/toast-context";

/**
 * Parse une réponse fetch en JSON de manière sécurisée
 * Gère le cas où le serveur retourne du HTML (erreur 529 overloaded)
 */
async function safeParseJson(response: Response): Promise<{ data?: any; error?: string }> {
  const contentType = response.headers.get("content-type") || "";

  // Si ce n'est pas du JSON, retourner une erreur appropriée
  if (!contentType.includes("application/json")) {
    const text = await response.text();
    // Détecter les pages d'erreur HTML
    if (text.includes("<html") || text.includes("<!DOCTYPE")) {
      return { error: "L'API IA est temporairement surchargée. Veuillez réessayer dans quelques minutes." };
    }
    return { error: text || "Réponse invalide du serveur" };
  }

  try {
    const data = await response.json();
    return { data };
  } catch {
    return { error: "Erreur lors du parsing de la réponse" };
  }
}

/**
 * Type definition for an image proposal returned by the API
 *
 * Each proposal represents a temporary image generated by DALL-E
 * that can be previewed and selected by the user.
 *
 * @property {string} id - Unique identifier for this proposal
 * @property {string} tempPath - Temporary file path in /public/images/blog/temp/
 * @property {string} size - Human-readable file size (e.g., "245 KB")
 * @property {string} dimensions - Image dimensions (e.g., "1024x1024")
 * @property {number} timestamp - Unix timestamp of generation
 */
export interface ImageProposal {
  id: string;
  tempPath: string;
  size: string;
  dimensions: string;
  timestamp: number;
}

/**
 * Type definition for form data used in image generation
 *
 * Only includes fields relevant to image generation workflow.
 */
interface FormData {
  title: string;
  content: string;
  slug?: string;
  category: string;
  tags: string[];
  seoIntent?: string;
  persona?: string;
  tones?: string[];
  imagePrompt?: string;
  image?: string;
}

/**
 * Type definition for toast notification structure
 *
 * Used for displaying feedback messages to the user.
 */
interface ToastNotification {
  title: string;
  description?: string;
  variant: "success" | "error" | "info";
}

/**
 * Props for the useImageGeneration hook
 *
 * @property {FormData} formData - Current form data (needed for article context)
 * @property {Function} updateFormData - Callback to update form with generated image path
 */
interface UseImageGenerationProps {
  formData: FormData;
  updateFormData: (update: Partial<FormData>) => void;
}

/**
 * Return type for the useImageGeneration hook
 *
 * @property {boolean} isGeneratingImages - Loading state for image generation
 * @property {ImageProposal[]} imageProposals - Array of generated image proposals
 * @property {boolean} isImageSelectionOpen - Modal visibility state
 * @property {boolean} isConfirmingSelection - Loading state for confirming selection
 * @property {boolean} isGeneratingPrompt - Loading state for prompt generation
 * @property {Function} setIsImageSelectionOpen - Control modal visibility
 * @property {Function} generateImagePrompt - Generate AI prompt from article
 * @property {Function} generateImages - Generate 3 DALL-E images
 * @property {Function} confirmImageSelection - Confirm and save selected image
 * @property {Function} regenerateImages - Regenerate with same prompt
 */
interface UseImageGenerationReturn {
  isGeneratingImages: boolean;
  imageProposals: ImageProposal[];
  isImageSelectionOpen: boolean;
  isConfirmingSelection: boolean;
  isGeneratingPrompt: boolean;
  setIsImageSelectionOpen: (open: boolean) => void;
  generateImagePrompt: () => Promise<void>;
  generateImages: () => Promise<void>;
  confirmImageSelection: (proposal: ImageProposal) => Promise<void>;
  regenerateImages: () => void;
}

/**
 * Custom hook for managing image generation and selection workflow.
 *
 * This hook handles:
 * - Generating image prompts from article content using AI
 * - Generating multiple image proposals using DALL-E
 * - Managing image selection state
 * - Confirming and saving selected images
 * - Regenerating images if needed
 *
 * @param formData - Current form data
 * @param updateFormData - Function to update form data
 * @returns Object containing state and handlers for image generation workflow
 *
 * @example
 * ```tsx
 * const {
 *   isGeneratingImages,
 *   imageProposals,
 *   generateImagePrompt,
 *   generateImages,
 *   confirmImageSelection,
 * } = useImageGeneration(formData, updateFormData);
 * ```
 */
export function useImageGeneration(
  formData: FormData,
  updateFormData: (update: Partial<FormData>) => void
): UseImageGenerationReturn {
  const { addToast } = useToast();

  // State for image generation workflow
  // Each state tracks a different phase of the image generation pipeline
  const [isGeneratingImages, setIsGeneratingImages] = useState(false); // DALL-E image generation
  const [imageProposals, setImageProposals] = useState<ImageProposal[]>([]); // Temporary image proposals
  const [isImageSelectionOpen, setIsImageSelectionOpen] = useState(false); // Selection modal visibility
  const [isConfirmingSelection, setIsConfirmingSelection] = useState(false); // Moving temp to final
  const [isGeneratingPrompt, setIsGeneratingPrompt] = useState(false); // AI prompt generation

  /**
   * Generates an AI-powered image prompt based on the article content.
   *
   * This function sends the article's title, content, category, tags, and metadata
   * to the API which uses AI to generate an appropriate image prompt.
   *
   * Requirements:
   * - Article must have a title and content
   *
   * API Endpoint: POST /api/blog/generate-prompt
   *
   * @throws {Error} If the API request fails or returns invalid data
   */
  const generateImagePrompt = useCallback(async () => {
    // Validate required fields before generating prompt
    if (!formData.title?.trim() || !formData.content?.trim()) {
      addToast({
        title: "Veuillez remplir au moins le titre et le contenu de l'article",
        variant: "error",
      });
      return;
    }

    setIsGeneratingPrompt(true);

    try {
      // Send article data to AI for prompt generation
      const response = await fetch("/api/blog/generate-prompt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: formData.title,
          content: formData.content,
          category: formData.category,
          tags: formData.tags,
          seoIntent: formData.seoIntent,
          persona: formData.persona,
          tones: formData.tones,
        }),
      });

      const { data, error: parseError } = await safeParseJson(response);

      if (!response.ok || parseError) {
        throw new Error(parseError || data?.error || "Erreur lors de la génération du prompt");
      }

      // Validate response data structure
      if (!data?.success || !data.imagePrompt) {
        throw new Error("Aucun prompt n'a pu être généré");
      }

      // Update form with generated prompt (user can edit before generating images)
      updateFormData({ imagePrompt: data.imagePrompt });

      addToast({
        title: "Prompt image généré avec succès",
        description: "Vous pouvez maintenant générer les images ou affiner le prompt",
        variant: "success",
      });
    } catch (error) {
      console.error("Error generating image prompt:", error);
      addToast({
        title: error instanceof Error ? error.message : "Échec de la génération du prompt",
        variant: "error",
      });
    } finally {
      setIsGeneratingPrompt(false);
    }
  }, [formData, updateFormData, addToast]);

  /**
   * Generates multiple image proposals using DALL-E based on the image prompt.
   *
   * This function sends the image prompt and slug to the API which generates
   * 3 image proposals. The generated images are stored temporarily and can be
   * previewed in the selection modal.
   *
   * Requirements:
   * - Image prompt must be filled
   * - Article slug must exist
   *
   * API Endpoint: POST /api/blog/generate-image
   *
   * @throws {Error} If the API request fails or no images are generated
   */
  const generateImages = useCallback(async () => {
    // Validate image prompt is present
    if (!formData.imagePrompt?.trim()) {
      addToast({
        title: "Veuillez renseigner un prompt image",
        variant: "error",
      });
      return;
    }

    // Validate slug is present (needed for temp file naming)
    if (!formData.slug?.trim()) {
      addToast({
        title: "Veuillez d'abord générer un slug pour l'article",
        variant: "error",
      });
      return;
    }

    setIsGeneratingImages(true);

    try {
      // Call DALL-E API to generate 3 image proposals
      const response = await fetch("/api/blog/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          imagePrompt: formData.imagePrompt,
          slug: formData.slug,
        }),
      });

      const { data, error: parseError } = await safeParseJson(response);

      if (!response.ok || parseError) {
        throw new Error(parseError || data?.message || "Erreur lors de la génération des images");
      }

      // Validate we received image proposals
      if (!data?.success || !data.proposals || data.proposals.length === 0) {
        throw new Error("Aucune image n'a pu être générée");
      }

      // Store proposals and open selection modal for user to choose
      setImageProposals(data.proposals);
      setIsImageSelectionOpen(true);

      addToast({
        title: `${data.proposals.length} proposition${data.proposals.length > 1 ? 's' : ''} générée${data.proposals.length > 1 ? 's' : ''} avec succès`,
        variant: "success",
      });
    } catch (error) {
      console.error("Error generating images:", error);
      addToast({
        title: error instanceof Error ? error.message : "Échec de la génération des images",
        variant: "error",
      });
    } finally {
      setIsGeneratingImages(false);
    }
  }, [formData.imagePrompt, formData.slug, addToast]);

  /**
   * Confirms the selection of an image proposal and saves it to the final location.
   *
   * This function sends the selected proposal to the API which moves the temporary
   * image to the final location (/public/images/blog/{slug}.webp) and returns
   * the final path.
   *
   * The form data is updated with the final image path, and the selection modal
   * is closed.
   *
   * API Endpoint: POST /api/blog/confirm-image-selection
   *
   * @param proposal - The selected image proposal to confirm
   * @throws {Error} If the API request fails or image cannot be saved
   */
  const confirmImageSelection = useCallback(async (proposal: ImageProposal) => {
    setIsConfirmingSelection(true);

    try {
      // Send selected proposal to API to move from temp to final location
      const response = await fetch("/api/blog/confirm-image-selection", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          selectedProposalId: proposal.id,
          tempPath: proposal.tempPath,
          slug: formData.slug,
        }),
      });

      const { data, error: parseError } = await safeParseJson(response);

      if (!response.ok || parseError) {
        throw new Error(parseError || data?.message || "Erreur lors de la sauvegarde de l'image");
      }

      // Validate we received final image path
      if (!data?.success || !data.finalPath) {
        throw new Error("Impossible de sauvegarder l'image");
      }

      // Update form data with final image path (e.g., /images/blog/my-article.webp)
      updateFormData({ image: data.finalPath });

      // Clean up: close modal and clear temporary proposals
      setIsImageSelectionOpen(false);
      setImageProposals([]);

      addToast({
        title: "Image sauvegardée avec succès",
        variant: "success",
      });
    } catch (error) {
      console.error("Error confirming image selection:", error);
      addToast({
        title: error instanceof Error ? error.message : "Échec de la sauvegarde de l'image",
        variant: "error",
      });
    } finally {
      setIsConfirmingSelection(false);
    }
  }, [formData.slug, updateFormData, addToast]);

  /**
   * Regenerates images by closing the current selection modal and triggering
   * a new image generation with the same prompt.
   *
   * This is useful when the user is not satisfied with the current proposals
   * and wants to try generating new images. The same prompt is used, but DALL-E
   * will generate different variations.
   *
   * **Workflow:**
   * 1. Close current selection modal
   * 2. Clear existing proposals
   * 3. Trigger new generation with same prompt
   */
  const regenerateImages = useCallback(() => {
    // Close modal and clear old proposals
    setIsImageSelectionOpen(false);
    setImageProposals([]);
    // Generate new images with same prompt
    generateImages();
  }, [generateImages]);

  return {
    isGeneratingImages,
    imageProposals,
    isImageSelectionOpen,
    isConfirmingSelection,
    isGeneratingPrompt,
    setIsImageSelectionOpen,
    generateImagePrompt,
    generateImages,
    confirmImageSelection,
    regenerateImages,
  };
}
