/**
 * Mapping des principales villes françaises vers leur numéro de département.
 * Utilisé pour afficher le département dans les analytics de géolocalisation.
 */
const FRENCH_CITY_DEPARTMENTS: Record<string, string> = {
  Paris: '75',
  Marseille: '13',
  Lyon: '69',
  Toulouse: '31',
  Nice: '06',
  Nantes: '44',
  Montpellier: '34',
  Strasbourg: '67',
  Bordeaux: '33',
  Lille: '59',
  Rennes: '35',
  Reims: '51',
  Toulon: '83',
  'Le Havre': '76',
  Grenoble: '38',
  Dijon: '21',
  Angers: '49',
  Villeurbanne: '69',
  'Clermont-Ferrand': '63',
  'Aix-en-Provence': '13',
  Brest: '29',
  'Le Mans': '72',
  Amiens: '80',
  Tours: '37',
  Limoges: '87',
  Metz: '57',
  Perpignan: '66',
  Orléans: '45',
  Rouen: '76',
  Caen: '14',
  Mulhouse: '68',
  Nancy: '54',
  Argenteuil: '95',
  Montreuil: '93',
  Roubaix: '59',
  Tourcoing: '59',
  Avignon: '84',
  Dunkerque: '59',
  Versailles: '78',
  Poitiers: '86',
  Pau: '64',
  'La Rochelle': '17',
  Cannes: '06',
  Antibes: '06',
  Calais: '62',
  Ajaccio: '2A',
  Bastia: '2B',
  Colmar: '68',
  Valence: '26',
  Troyes: '10',
  Quimper: '29',
  Auxerre: '89',
  Joigny: '89',
  Migennes: '89',
  Sens: '89',
  Besançon: '25',
  'Saint-Denis': '93',
  Nanterre: '92',
  'Boulogne-Billancourt': '92',
  Créteil: '94',
  'Saint-Étienne': '42',
  Nîmes: '30',
  Béziers: '34',
  'Saint-Malo': '35',
  Lorient: '56',
  Vannes: '56',
  'Saint-Nazaire': '44',
  'La Roche-sur-Yon': '85',
  Chartres: '28',
  Bourges: '18',
  Châteauroux: '36',
  Nevers: '58',
  Mâcon: '71',
  'Chalon-sur-Saône': '71',
  Annecy: '74',
  Chambéry: '73',
  'Thonon-les-Bains': '74',
  Gap: '05',
  'Digne-les-Bains': '04',
  Arles: '13',
  Fréjus: '83',
  Carcassonne: '11',
  Tarbes: '65',
  Albi: '81',
  Rodez: '12',
  Cahors: '46',
  Agen: '47',
  'Mont-de-Marsan': '40',
  Bayonne: '64',
  Biarritz: '64',
  Périgueux: '24',
  Angoulême: '16',
  Niort: '79',
  Châtellerault: '86',
  Blois: '41',
  Laval: '53',
  Cholet: '49',
  Saumur: '49',
  'Le Puy-en-Velay': '43',
  Aurillac: '15',
  Montluçon: '03',
  Vichy: '03',
  Moulins: '03',
  Guéret: '23',
  Tulle: '19',
  'Brive-la-Gaillarde': '19',
  Évreux: '27',
  Cherbourg: '50',
  Alençon: '61',
  'Saint-Lô': '50',
  Lisieux: '14',
  Compiègne: '60',
  Beauvais: '60',
  Laon: '02',
  'Saint-Quentin': '02',
  Soissons: '02',
  'Charleville-Mézières': '08',
  Épernay: '51',
  'Châlons-en-Champagne': '51',
  'Bar-le-Duc': '55',
  Verdun: '55',
  Épinal: '88',
  'Saint-Dié-des-Vosges': '88',
  Belfort: '90',
  'Lons-le-Saunier': '39',
  Vesoul: '70',
  Auxonne: '21',
  Pontarlier: '25',
  Montbéliard: '25',
  Thionville: '57',
  Forbach: '57',
  Haguenau: '67',
  Sélestat: '67',
  Saverne: '67',
  Douai: '59',
  Valenciennes: '59',
  Cambrai: '59',
  Arras: '62',
  Lens: '62',
  Béthune: '62',
  'Boulogne-sur-Mer': '62',
  Abbeville: '80',
  'Saint-Brieuc': '22',
  Lannion: '22',
  Morlaix: '29',
  Pontivy: '56',
  Vitré: '35',
  Fougères: '35',
  'Saint-Raphaël': '83',
  Draguignan: '83',
  Grasse: '06',
  Menton: '06',
  'Salon-de-Provence': '13',
  Martigues: '13',
  Istres: '13',
  Sète: '34',
  Lunel: '34',
  Alès: '30',
  Narbonne: '11',
  Foix: '09',
  Auch: '32',
  Lourdes: '65',
  Castres: '81',
  Millau: '12',
  Figeac: '46',
  'Villeneuve-sur-Lot': '47',
  Bergerac: '24',
  'Sarlat-la-Canéda': '24',
  Dax: '40',
  Arcachon: '33',
  Libourne: '33',
  Rochefort: '17',
  Saintes: '17',
  Cognac: '16',
  Bressuire: '79',
  Parthenay: '79',
  'Fontenay-le-Comte': '85',
  "Les Sables-d'Olonne": '85',
  'Saint-Pierre': '974',
  'Saint-Denis de la Réunion': '974',
  'Fort-de-France': '972',
  'Pointe-à-Pitre': '971',
  Cayenne: '973',
  Mamoudzou: '976',
};

/** Regex pour valider un numéro de département français */
const DEPARTMENT_PATTERN = /^(\d{2,3}|2[AB])$/i;

/**
 * Détermine le numéro de département français à partir du regionCode ou du nom de ville.
 * Retourne le numéro de département ou null si indéterminable.
 */
export function getFrenchDepartment(city: string, regionCode?: string | null): string | null {
  if (regionCode && DEPARTMENT_PATTERN.test(regionCode)) {
    return regionCode.toUpperCase();
  }
  return FRENCH_CITY_DEPARTMENTS[city] ?? null;
}
