#!/usr/bin/env node

/**
 * Kairn CLI
 *
 * Command-line interface for managing Kairn platform sites.
 *
 * Commands:
 * - init: Create a new site from template
 * - dev: Start development server
 * - build: Build for production
 * - db:migrate: Run database migrations
 * - db:seed: Seed the database
 * - db:push: Push schema changes
 * - db:studio: Open Prisma Studio
 * - generate:page: Generate a new page
 * - generate:component: Generate a new component
 * - config:create: Create a site configuration
 * - config:validate: Validate a configuration file
 * - templates: List available templates
 * - palettes: List available color palettes
 */

import { writeFile, readFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';

import {
  SITE_TEMPLATES,
  COLOR_PALETTES,
  createConfigFromTemplate,
  validateSiteConfig,
  safeParseSiteConfig,
  type SiteTemplate,
  type SiteConfig,
  type ColorPalette,
} from '@kairn/core';
import chalk from 'chalk';
import { Command } from 'commander';
import inquirer from 'inquirer';
import ora from 'ora';

type SiteTemplateConfig = (typeof SITE_TEMPLATES)[SiteTemplate];

import { buildCommand } from './commands/build';
import { migrateCommand, seedCommand, pushCommand, generateCommand as dbGenerateCommand, studioCommand } from './commands/db';
import { devCommand } from './commands/dev';
import { generatePageCommand, generateComponentCommand } from './commands/generate';
import { initCommand } from './commands/init';
import { fileExists } from './utils/fs';
import { success, error, header, formatJson } from './utils/log';

const program = new Command();

// =============================================================================
// Legacy Config Commands (kept for backwards compatibility)
// =============================================================================

function getTemplateDescription(template: SiteTemplate): string {
  const descriptions: Record<SiteTemplate, string> = {
    psychologist: 'Calm and professional, ideal for therapists and psychologists',
    holistic: 'Natural and organic, perfect for holistic practitioners',
    medical: 'Modern and clean, suitable for medical professionals',
    minimal: 'Simple and focused, great for personal practice sites',
  };
  return descriptions[template];
}

function configToEnv(config: SiteConfig): string {
  const lines: string[] = [
    '# Kairn Site Configuration',
    `# Generated for: ${config.name}`,
    '',
    `SITE_SLUG=${config.slug}`,
    `SITE_NAME=${config.name}`,
    config.domain ? `SITE_DOMAIN=${config.domain}` : '',
    `SITE_LOCALE=${config.locale}`,
    '',
    '# Theme',
    `SITE_PRIMARY_COLOR=${config.theme.colors.light.primary}`,
    '',
    '# Contact',
    config.contact.email ? `SITE_CONTACT_EMAIL=${config.contact.email}` : '',
    config.contact.phone ? `SITE_CONTACT_PHONE=${config.contact.phone}` : '',
    '',
    '# Integrations',
    config.integrations.googleAnalytics.measurementId
      ? `GOOGLE_ANALYTICS_ID=${config.integrations.googleAnalytics.measurementId}`
      : '',
  ];

  return lines.filter(Boolean).join('\n');
}

function configToTypeScript(config: SiteConfig): string {
  return `/**
 * Site Configuration for ${config.name}
 * Generated by @kairn/cli
 */

import type { SiteConfig } from '@kairn/core';

export const siteConfig: SiteConfig = ${formatJson(config)} as const;

export default siteConfig;
`;
}

/**
 * Create a new site configuration interactively (legacy command)
 */
async function createConfig(options: { output?: string; template?: string }): Promise<void> {
  header('🚀 Create a new Kairn configuration');

  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'slug',
      message: 'Site slug (lowercase, no spaces):',
      validate: (input: string) => {
        if (!/^[a-z0-9-]+$/.test(input)) {
          return 'Slug must be lowercase alphanumeric with hyphens only';
        }
        return true;
      },
    },
    {
      type: 'input',
      name: 'name',
      message: 'Site name:',
      validate: (input: string) => input.length > 0 || 'Name is required',
    },
    {
      type: 'input',
      name: 'domain',
      message: 'Domain (optional):',
    },
    {
      type: 'list',
      name: 'template',
      message: 'Choose a template:',
      choices: Object.keys(SITE_TEMPLATES).map((t) => ({
        name: `${t.charAt(0).toUpperCase() + t.slice(1)} - ${getTemplateDescription(t as SiteTemplate)}`,
        value: t,
      })),
      default: options.template || 'psychologist',
    },
    {
      type: 'list',
      name: 'colorPalette',
      message: 'Choose a color palette:',
      choices: Object.keys(COLOR_PALETTES).map((p) => ({
        name: `${p.charAt(0).toUpperCase() + p.slice(1)} - Primary: ${COLOR_PALETTES[p as keyof typeof COLOR_PALETTES].primary}`,
        value: p,
      })),
    },
    {
      type: 'input',
      name: 'seoTitle',
      message: 'SEO title:',
      default: (answers: { name: string }) => answers.name,
    },
    {
      type: 'input',
      name: 'seoDescription',
      message: 'SEO description (optional):',
    },
    {
      type: 'input',
      name: 'email',
      message: 'Contact email (optional):',
    },
    {
      type: 'input',
      name: 'phone',
      message: 'Contact phone (optional):',
    },
  ]);

  const spinner = ora('Creating site configuration...').start();

  try {
    const config = createConfigFromTemplate(answers.template as SiteTemplate, {
      slug: answers.slug,
      name: answers.name,
      domain: answers.domain || undefined,
      seo: {
        title: answers.seoTitle,
        description: answers.seoDescription || undefined,
      },
      contact: {
        email: answers.email || undefined,
        phone: answers.phone || undefined,
      },
    });

    const palette = COLOR_PALETTES[answers.colorPalette as keyof typeof COLOR_PALETTES];
    if (config.theme) {
      config.theme.colors = { light: palette };
    }

    const validatedConfig = validateSiteConfig(config);
    const outputPath = options.output || join(process.cwd(), `${answers.slug}.config.json`);

    const dir = dirname(outputPath);
    if (dir !== '.') {
      await mkdir(dir, { recursive: true });
    }

    await writeFile(outputPath, formatJson(validatedConfig), 'utf-8');

    spinner.succeed(`Site configuration created!`);
    success(`Configuration saved to: ${chalk.cyan(outputPath)}`);

    console.log('\n' + chalk.bold('Next steps:'));
    console.log('  1. Review and customize the configuration file');
    console.log('  2. Use "kairn init <name>" to scaffold a full site');
    console.log('');
  } catch (err) {
    spinner.fail('Failed to create site configuration');
    error((err as Error).message);
    process.exit(1);
  }
}

/**
 * Validate a site configuration file
 */
async function validateConfig(filePath: string): Promise<void> {
  const spinner = ora(`Validating ${filePath}...`).start();

  try {
    if (!(await fileExists(filePath))) {
      spinner.fail('File not found');
      error(`Configuration file not found: ${filePath}`);
      process.exit(1);
    }

    const content = await readFile(filePath, 'utf-8');
    let config: unknown;

    try {
      config = JSON.parse(content);
    } catch {
      spinner.fail('Invalid JSON');
      error('Configuration file is not valid JSON');
      process.exit(1);
    }

    const result = safeParseSiteConfig(config);

    if (result.success) {
      spinner.succeed('Configuration is valid!');
      success(`Site: ${result.data.name} (${result.data.slug})`);

      console.log('\n' + chalk.bold('Configuration Summary:'));
      console.log(`  Domain: ${result.data.domain || 'Not set'}`);
      console.log(`  Locale: ${result.data.locale}`);
      console.log(`  Features enabled: ${Object.entries(result.data.features).filter(([, v]) => v).map(([k]) => k).join(', ')}`);
      console.log(`  Dark mode: ${result.data.theme.darkModeEnabled ? 'Enabled' : 'Disabled'}`);
      console.log('');
    } else {
      spinner.fail('Configuration is invalid');

      console.log('\n' + chalk.bold('Validation Errors:'));
      for (const issue of result.error.issues) {
        console.log(chalk.red(`  • ${issue.path.join('.')}: ${issue.message}`));
      }
      console.log('');
      process.exit(1);
    }
  } catch (err) {
    spinner.fail('Validation failed');
    error((err as Error).message);
    process.exit(1);
  }
}

/**
 * List available templates
 */
function listTemplates(): void {
  header('📋 Available Site Templates');

  for (const [name, template] of Object.entries(SITE_TEMPLATES) as [SiteTemplate, SiteTemplateConfig][]) {
    console.log(chalk.cyan(`  ${name}`));
    console.log(`    Description: ${getTemplateDescription(name)}`);
    console.log(`    Features: ${Object.entries(template.features).filter(([, v]) => v).map(([k]) => k).join(', ')}`);
    console.log(`    Hero style: ${template.content.hero.style}`);
    console.log('');
  }
}

/**
 * List available color palettes
 */
function listPalettes(): void {
  header('🎨 Available Color Palettes');

  for (const [name, palette] of Object.entries(COLOR_PALETTES) as [string, ColorPalette][]) {
    console.log(chalk.cyan(`  ${name}`));
    console.log(`    Primary:     ${chalk.hex(palette.primary)('████')} ${palette.primary}`);
    console.log(`    Secondary:   ${palette.secondary ? chalk.hex(palette.secondary)('████') + ' ' + palette.secondary : 'Not set'}`);
    console.log(`    Accent:      ${palette.accent ? chalk.hex(palette.accent)('████') + ' ' + palette.accent : 'Not set'}`);
    console.log(`    Background:  ${chalk.hex(palette.background)('████')} ${palette.background}`);
    console.log('');
  }
}

/**
 * Export configuration to different formats
 */
async function exportConfig(
  inputPath: string,
  options: { format?: string; output?: string }
): Promise<void> {
  const spinner = ora('Exporting configuration...').start();

  try {
    const content = await readFile(inputPath, 'utf-8');
    const config = validateSiteConfig(JSON.parse(content));

    let output: string;
    let extension: string;

    switch (options.format) {
      case 'env':
        output = configToEnv(config);
        extension = '.env';
        break;
      case 'ts':
        output = configToTypeScript(config);
        extension = '.ts';
        break;
      case 'json':
      default:
        output = formatJson(config);
        extension = '.json';
    }

    const outputPath = options.output || `${config.slug}.config${extension}`;
    await writeFile(outputPath, output, 'utf-8');

    spinner.succeed(`Exported to ${outputPath}`);
  } catch (err) {
    spinner.fail('Export failed');
    error((err as Error).message);
    process.exit(1);
  }
}

// =============================================================================
// CLI Setup
// =============================================================================

program
  .name('kairn')
  .description('CLI tool for managing Kairn platform sites')
  .version('0.1.0');

// =============================================================================
// Main Commands
// =============================================================================

program
  .command('init <site-name>')
  .description('Create a new site from template')
  .option('-t, --template <name>', 'Use a specific template')
  .option('-f, --force', 'Overwrite existing site')
  .action(initCommand);

program
  .command('dev')
  .description('Start development server')
  .option('-s, --site <name>', 'Site to run')
  .option('-p, --port <port>', 'Port to run on')
  .option('--turbo', 'Run all sites with Turbo')
  .action(devCommand);

program
  .command('build')
  .description('Build for production')
  .option('-s, --site <name>', 'Site to build')
  .option('--turbo', 'Build all with Turbo (default)')
  .action(buildCommand);

// =============================================================================
// Database Commands
// =============================================================================

const db = program.command('db').description('Database management commands');

db.command('migrate')
  .description('Run database migrations')
  .option('-n, --name <name>', 'Migration name (for dev)')
  .option('--deploy', 'Deploy migrations (for production)')
  .action(migrateCommand);

db.command('push')
  .description('Push schema changes without migrations (dev only)')
  .action(pushCommand);

db.command('seed')
  .description('Seed the database with initial data')
  .option('--reset', 'Reset database before seeding')
  .action(seedCommand);

db.command('generate')
  .description('Generate Prisma client')
  .action(dbGenerateCommand);

db.command('studio')
  .description('Open Prisma Studio')
  .action(studioCommand);

// =============================================================================
// Generate Commands
// =============================================================================

const generate = program.command('generate').description('Generate code scaffolds');

generate
  .command('page <name>')
  .description('Generate a new page')
  .option('-s, --site <name>', 'Target site')
  .option('-r, --route <path>', 'Route path (defaults to kebab-case of name)')
  .action(generatePageCommand);

generate
  .command('component <name>')
  .description('Generate a new component')
  .option('-s, --site <name>', 'Target site')
  .option('-t, --type <type>', 'Component type: client or server', 'server')
  .action(generateComponentCommand);

// =============================================================================
// Config Commands (Legacy - for backwards compatibility)
// =============================================================================

const config = program.command('config').description('Configuration management');

config
  .command('create')
  .description('Create a new site configuration interactively')
  .option('-o, --output <path>', 'Output file path')
  .option('-t, --template <name>', 'Use a specific template')
  .action(createConfig);

config
  .command('validate <file>')
  .description('Validate a site configuration file')
  .action(validateConfig);

config
  .command('export <file>')
  .description('Export configuration to different formats')
  .option('-f, --format <format>', 'Output format (json, env, ts)', 'json')
  .option('-o, --output <path>', 'Output file path')
  .action(exportConfig);

// =============================================================================
// Reference Commands
// =============================================================================

program
  .command('templates')
  .description('List available site templates')
  .action(listTemplates);

program
  .command('palettes')
  .description('List available color palettes')
  .action(listPalettes);

// =============================================================================
// Version and Help
// =============================================================================

program.addHelpText('after', `
${chalk.bold('Examples:')}
  ${chalk.gray('$')} kairn init my-site                    ${chalk.gray('# Create a new site')}
  ${chalk.gray('$')} kairn dev --site my-site              ${chalk.gray('# Start dev server')}
  ${chalk.gray('$')} kairn build                           ${chalk.gray('# Build all sites')}
  ${chalk.gray('$')} kairn db migrate --name add-users     ${chalk.gray('# Create migration')}
  ${chalk.gray('$')} kairn db seed                         ${chalk.gray('# Seed database')}
  ${chalk.gray('$')} kairn generate page about             ${chalk.gray('# Generate a page')}
  ${chalk.gray('$')} kairn generate component Header       ${chalk.gray('# Generate component')}

${chalk.bold('Documentation:')}
  ${chalk.cyan('https://github.com/your-org/kairn')}
`);

program.parse();
